import React from "react";
import { View, Text, StyleSheet } from "react-native";
import { useRoute } from "@react-navigation/native";
import CustomButton from "./CustomButton";

const ReportDetail = () => {
  const route = useRoute();
  const { report } = route.params;

  const exportReport = (format) => {
    // Logic to export report in the chosen format (PDF, Excel, Word)
  };

  const printReport = () => {
    // Logic to print the report
  };

  return (
    <View style={styles.container}>
      <Text style={styles.title}>{report.reportName}</Text>
      <Text>Generated Date: {report.generatedDate}</Text>
      <Text>Generated By: {report.generatedBy}</Text>
      {/* Display more details here */}
      <View style={styles.buttonContainer}>
        <CustomButton onPress={() => exportReport("PDF")} iconName="file-pdf-o">
          Export as PDF
        </CustomButton>
        <CustomButton
          onPress={() => exportReport("Excel")}
          iconName="file-excel-o"
        >
          Export as Excel
        </CustomButton>
        <CustomButton
          onPress={() => exportReport("Word")}
          iconName="file-word-o"
        >
          Export as Word
        </CustomButton>
        <CustomButton onPress={printReport} iconName="print">
          Print
        </CustomButton>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: "#FFF8DC",
  },
  title: {
    fontSize: 24,
    marginBottom: 20,
    color: "#000",
  },
  buttonContainer: {
    marginVertical: 10,
    alignItems: "center",
  },
});

export default ReportDetail;
