import React from "react";
import { View, Text, StyleSheet, FlatList } from "react-native";
import { useNavigation } from "@react-navigation/native";
import CustomButton from "./CustomButton"; // CustomButton component as previously defined

const ReportScreen = () => {
  const navigation = useNavigation();
  const reports = [
    // Sample data
    {
      reportID: "1",
      reportName: "Crime Scene Report - Case 123",
      generatedDate: "2024-08-01",
      generatedBy: "John Doe",
    },
    // Add more reports here
  ];

  return (
    <View style={styles.container}>
      <Text style={styles.title}>Reports</Text>
      <FlatList
        data={reports}
        keyExtractor={(item) => item.reportID}
        renderItem={({ item }) => (
          <View style={styles.reportItem}>
            <Text>Name: {item.reportName}</Text>
            <Text>Date: {item.generatedDate}</Text>
            <Text>Generated By: {item.generatedBy}</Text>
            <CustomButton
              active={false}
              onPress={() =>
                navigation.navigate("ReportDetail", { report: item })
              }
              iconName="file"
            >
              View Report
            </CustomButton>
          </View>
        )}
      />
      <View style={styles.buttonContainer}>
        <CustomButton
          active={false}
          onPress={() => navigation.navigate("GenerateReport")}
          iconName="plus"
        >
          Generate New Report
        </CustomButton>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: "#FFF8DC",
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 20,
    color: "#000",
  },
  reportItem: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
    marginBottom: 10,
  },
  buttonContainer: {
    marginVertical: 10,
    width: "80%",
    alignSelf: "center",
  },
});

export default ReportScreen;
